on: 
  workflow_dispatch:
    inputs:
      device:
        description: 'Select device'     
        required: true
        type: choice
        options:
        - AX1800
        - AXT1800
        - MT2500
        - MT3000
        - SF1200
        - SFT1200
      sourcecode:
        description: 'Source code URL'     
        required: true
      pkgname:
        description: 'Openwrt package name'  
        required: true
      email:
        description: 'Git accuont email address'  
        required: false
      password:
        description: 'Git account password'  
        required: false
        
jobs:
  setpackage:
    runs-on: ubuntu-20.04

    env:
      SOURCECODEURL: ${{ github.event.inputs.sourcecode }}
      PKGNAME: ${{ github.event.inputs.pkgname }}
      BOARD: ${{ github.event.inputs.device }}
      EMAIL: ${{ github.event.inputs.email }}
      PASSWORD: ${{ github.event.inputs.password }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Download gl-sdk
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ./build.sh
        ./build.sh

    - name: Update ./scripts/feeds
      run: ./scripts/feeds update -a

    - name: Install ./scripts/feeds
      run: ./scripts/feeds install -a

    - name: Make defconfig
      run: |
        echo CONFIG_ALL=y >.config
        make defconfig
        
    - name: Make ./package/feeds/luci/luci-base/compile
      run: make V=s ./package/feeds/luci/luci-base/compile

    - name: Make ./package/feeds/githubaction/${PKGNAME}/compile
      run: make V=s ./package/feeds/githubaction/${PKGNAME}/compile

    - name: Outputs
      run: |
        find bin -type f -exec ls -lh {} \;
        find bin -type f -name "*.ipk" -exec cp -f {} "${WORKDIR}" \; 

    - name: Upload Artefacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.pkgname }}_related_ipks
        path: |
          ./*ipk*
