on: 
  workflow_dispatch:
    inputs:
      device:
        description: 'Select device'     
        required: true
        type: choice
        options:
        - MT2500
        - MT3000
        - AX1800
        - AXT1800
        - SF1200
        - SFT1200
      sourcecode:
        description: 'Source code URL'     
        required: true
      pkgname:
        description: 'Openwrt package name'  
        required: true
      email:
        description: 'Git account email address'
        required: false
      password:
        description: 'Git account password'  
        required: false

env:
  SOURCECODEURL: ${{ github.event.inputs.sourcecode }}
  PKGNAME: ${{ github.event.inputs.pkgname }}
  BOARD: ${{ github.event.inputs.device }}
  EMAIL: ${{ github.event.inputs.email }}
  PASSWORD: ${{ github.event.inputs.password }}

jobs:
  apt-get:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
  
      - name: Update System Packages
        run: |
          sudo -E apt-get update
          sudo -E apt-get install -y asciidoc bash bc binutils bzip2 fastjar flex gawk gcc genisoimage gettext git intltool jikespg libgtk2.0-dev libncurses5-dev libssl-dev
          sudo -E apt-get install -y make mercurial patch perl-modules python2.7-dev rsync ruby sdcc subversion unzip util-linux wget xsltproc zlib1g-dev zlib1g-dev

      - name: Restore Cache SDK
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ./openwrt-sdk/
          key: glsdk-${{ github.event.inputs.device }}
          
      - name: Get gl-sdk
        if: steps.cache-restore.outputs.cache-hit != 'true'
        working-directory: ./
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x ./build.sh
          ./build.sh

      - name: Acquire ./scripts/feeds
        if: steps.cache-restore.outputs.cache-hit != 'true'
        working-directory: ./openwrt-sdk
        run: |
          ./scripts/feeds update -a
        continue-on-error: true
  
      - name: Install ./scripts/feeds
        if: steps.cache-restore.outputs.cache-hit != 'true'
        working-directory: ./openwrt-sdk
        run: |
          ./scripts/feeds install -a
  
      - name: Make defconfig
        if: steps.cache-restore.outputs.cache-hit != 'true'
        working-directory: ./openwrt-sdk
        run: |
          echo CONFIG_ALL=y >.config
          make defconfig
  
      - name: Make ./package/feeds/luci/luci-base/compile
        if: steps.cache-restore.outputs.cache-hit != 'true'
        working-directory: ./openwrt-sdk
        run: |
          make V=s ./package/feeds/luci/luci-base/compile
  
      - name: Save Cache SDK
        if: steps.cache-restore.outputs.cache-hit != 'true'
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: ./openwrt-sdk/
          key: glsdk-${{ github.event.inputs.device }}

      - name: Get PKGNAME
        run: |
          mkdir -p  ${GITHUB_WORKSPACE}/buildsource
          cd ${GITHUB_WORKSPACE}/buildsource
          git clone "$SOURCECODEURL"
  
      - name: Install PKGNAME
        run: |
          cd $GITHUB_WORKSPACE/openwrt-sdk
          sed -i "1i\src-link githubaction ${GITHUB_WORKSPACE}/buildsource" feeds.conf.default
          echo Contents of "feeds.conf.default"
          cat feeds.conf.default

      - name: Print Folders in Working Directory
        run: |
          echo "Contents of '$(pwd)'"
          ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'

      - name: Make ./package/feeds/githubaction/${PKGNAME}/compile
        run: |
          cd $GITHUB_WORKSPACE/openwrt-sdk
          make V=s ./package/feeds/githubaction/${PKGNAME}/compile
  
      - name: Outputs
        run: |
          cd $GITHUB_WORKSPACE/openwrt-sdk
          find bin -type f -exec ls -lh {} \;
          find bin -type f -name "*.ipk" -exec cp -f {} "${GITHUB_WORKSPACE}/output_ipks" \; 
  
      - name: Upload Artefacts (IPKs)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.pkgname }}_related_ipks
          path: |
            ./output_ipks/*ipk*

      - name: Upload Artefacts (SDK)
        uses: actions/upload-artifact@v2
        with:
          name: glsdk-${{ github.event.inputs.device }}
          path: |
            ./openwrt-sdk/
