on: 
  workflow_dispatch:
    inputs:
      device:
        description: 'Select device'     
        required: true
        type: choice
        options:
        - AX1800
        - AXT1800
        - MT2500
        - MT3000
        - SF1200
        - SFT1200
      sourcecode:
        description: 'Source code URL'     
        required: true
      pkgname:
        description: 'Openwrt package name'  
        required: true
      email:
        description: 'Git account email address'
        required: false
      password:
        description: 'Git account password'  
        required: false
        
jobs:
  setpackage:
    runs-on: ubuntu-20.04

    env:
      SOURCECODEURL: ${{ github.event.inputs.sourcecode }}
      PKGNAME: ${{ github.event.inputs.pkgname }}
      BOARD: ${{ github.event.inputs.device }}
      EMAIL: ${{ github.event.inputs.email }}
      PASSWORD: ${{ github.event.inputs.password }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Update System Packages
      run: |
        sudo -E apt-get update
        sudo -E apt-get install -y asciidoc bash bc binutils bzip2 fastjar flex gawk gcc genisoimage gettext git intltool jikespg libgtk2.0-dev libncurses5-dev libssl-dev make mercurial patch perl-modules python2.7-dev rsync ruby sdcc subversion unzip util-linux wget xsltproc zlib1g-dev zlib1g-dev
        mkdir -p  ${GITHUB_WORKSPACE}/buildsource

    - name: Get PKGNAME
      working-directory: ./buildsource
      run: |
        git clone "$SOURCECODEURL"

    - name: Get gl-sdk
      working-directory: ./
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: Acquire ./scripts/feeds
      working-directory: ./openwrt-sdk
      run: |
        ./scripts/feeds update -a
      continue-on-error: true

    - name: Install ./scripts/feeds
      working-directory: ./openwrt-sdk
      run: |
        ./scripts/feeds install -a

    - name: Make defconfig
      working-directory: ./openwrt-sdk
      run: |
        echo CONFIG_ALL=y >.config
        make defconfig
        
    - name: Make ./package/feeds/luci/luci-base/compile
      working-directory: ./openwrt-sdk
      run: |
        make V=s ./package/feeds/luci/luci-base/compile

    - name: Make ./package/feeds/githubaction/${PKGNAME}/compile
      working-directory: ./openwrt-sdk
      run: |
        make V=s ./package/feeds/githubaction/${PKGNAME}/compile

    - name: Outputs
      working-directory: ./openwrt-sdk
      run: |
        find bin -type f -exec ls -lh {} \;
        find bin -type f -name "*.ipk" -exec cp -f {} "${GITHUB_WORKSPACE}" \; 

    - name: Upload Artefacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.pkgname }}_related_ipks
        path: |
          ./*ipk*
